#pragma only_renderers d3d11
#pragma kernel SSRTAOKernel
#pragma use_dxc
#pragma require inlineraytracing

#include "../Lib/CommonLib.hlsl"
#include "../Lib/BasicNoiseLib.hlsl"
#include "SSRTAOLib.hlsl"


[numthreads(8, 4, 1)]
void SSRTAOKernel (uint3 id : SV_DispatchThreadID)
{
    uint2 launchDim;
    rw_OutputRT.GetDimensions(launchDim.x, launchDim.y);

    if (any(id.xy >= launchDim))
        return;
        
    float depth = _CamDepthTexture[id.xy].r;
    
    if (depth <= 1e-8) 
    {
        rw_OutputRT[id.xy] = 1;
        return;
    }
    
    float2 uv = (id.xy + 0.5f) / float2(launchDim.x, launchDim.y);
    float4 clipPos = float4(uv * 2.0f - 1.0f, depth, 1.0f);
    clipPos.y = -clipPos.y;
    float4 worldPos4 = mul(_InvCameraVPMatrix, clipPos);
    float3 worldPos = worldPos4.xyz / worldPos4.w;
    
    float3 worldNormal = normalize(_CamNormalsTexture[id.xy].xyz);

    uint pixelSeed = (id.y * launchDim.x + id.x) * 114514;
    float2 pixelScramble = pcgHash2D(pixelSeed);
    
    float3 aoDir = GetR4CosineHemisphereDirectionWorld(worldNormal, _FrameIndex, pixelScramble);

    RayDesc aoRay;
    aoRay.Origin = worldPos + worldNormal * 1e-5f;
    aoRay.Direction = aoDir;
    aoRay.TMin = 0.0;
    aoRay.TMax = _AORadius;
    
    uint aoFlags = RAY_FLAG_CULL_BACK_FACING_TRIANGLES | RAY_FLAG_ACCEPT_FIRST_HIT_AND_END_SEARCH | RAY_FLAG_SKIP_CLOSEST_HIT_SHADER | RAY_FLAG_FORCE_OPAQUE;

    RayQuery<RAY_FLAG_CULL_BACK_FACING_TRIANGLES | RAY_FLAG_ACCEPT_FIRST_HIT_AND_END_SEARCH | RAY_FLAG_SKIP_CLOSEST_HIT_SHADER | RAY_FLAG_FORCE_OPAQUE> aoQuery; 
    aoQuery.TraceRayInline(_RTAccStruct, aoFlags, 0xFF, aoRay);
    aoQuery.Proceed();
    
    float currentAO = (aoQuery.CommittedStatus() == COMMITTED_TRIANGLE_HIT) ? 0.0 : 1.0;

    if (_FrameIndex > 1)
    {
        float hisAO = rw_OutputRT[id.xy].x;
        float weight = 1.0f / (float)_FrameIndex;
        currentAO = lerp(hisAO, currentAO, weight);
    }

    rw_OutputRT[id.xy] = float4(currentAO.xxx, 1.0);
}
